server:
  port: 3000

cross_origin:
  allowed_domain: http://localhost:8080

## PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datawheeldb?createDatabaseIfNotExist=true
    username: postgres
    password: Cps38102991
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: update
    generate-ddl: true
    show-sql: true


